package model

type Dragon struct {
	ID          int
	Name        string
	Species     string
	Class       string
	Description string
}

var Dragons = []Dragon{
	{ID: 1, Name: "Toothless", Species: "Night Fury", Class: "Strike", Description: "Loyal and empathic with boundless, puppy-like energy"},
	{ID: 2, Name: "Stormfly", Species: "Deadly Nadder", Class: "Tracker", Description: "Precise and cunning in battle, yet warm and affectionate with friends old and new"},
	{ID: 3, Name: "Hookfang", Species: "Monstrous Nightmare", Class: "Stoker", Description: "Incendiary in temperament and short on patience, Hookfang would rather ignite 1st and think 2nd"},
	{ID: 4, Name: "Barf & Belch", Species: "Hideous Zippleback", Class: "Mystery", Description: "Truly a split personality! Barf & Belch are each fiercely independent, yet inextricably linked"},
	{ID: 5, Name: "Meatlug", Species: "Gronckle", Class: "Boulder", Description: "Exceedingly demonstrative and sweet, yet quite self-conscious despite her thick hide"},
	{ID: 6, Name: " ", Species: "Light Fury", Class: "Strike", Description: "The feline-like Light Fury is gentle and playful by nature, like Toothless, but fiercely protective when danger is present"},
	{ID: 7, Name: "Grump", Species: "Hotburple", Class: "Boulder", Description: "A loyal, lava-launching helper -- when he isn't napping"},
	{ID: 8, Name: "Cloud Jumper", Species: "Stormcutter", Class: "Sharp", Description: "Proud and confidence"},
	{ID: 9, Name: "Skull Crusher", Species: "Rumblehorn", Class: "Tracker", Description: "Doggedly determined when he's caught a scent"},
	{ID: 10, Name: " ", Species: "Armor Wing", Class: "Mystery", Description: "Metal-Plated Plunderer"},
	{ID: 11, Name: " ", Species: "Eruptodon", Class: "Boulder", Description: "Volcanic & valiant"},
	{ID: 12, Name: " ", Species: "Night terror", Class: "Stoker", Description: "Shy at first, but great as allies once trust is built"},
	{ID: 13, Name: " ", Species: "Seashocker", Class: "Tidal", Description: "Masters of the sneak attack"},
	{ID: 14, Name: " ", Species: "Skrill", Class: "Strike", Description: "Belligerent and as unpredictable as lightning strikes"},
	{ID: 15, Name: " ", Species: "Snaptrapper", Class: "Mystery", Description: "Temptation and terror to the fourth power"},
	{ID: 16, Name: " ", Species: "Teribble Terror", Class: "Stoker", Description: "Inquisitive and curious animals, their only downfall is their territorial in-fighting"},
	{ID: 17, Name: " ", Species: "Thunderdrum", Class: "Tidal", Description: "Strident and assertive, the loud Thunderdrum always makes its feelings known"},
	{ID: 18, Name: " ", Species: "Timberjack", Class: "Sharp", Description: "Modest serenity balanced with fierce protection of their riders"},
	{ID: 19, Name: " ", Species: "Whispering Death", Class: "Boulder", Description: "Blindly aggressive and capable of holding a grudge like no other dragon"},
	{ID: 20, Name: "Drago's Bewilderbeast", Species: "Bewilderbeast", Class: "Tidal", Description: "Scarred and bred for battle"},
	{ID: 21, Name: "Valka's Bewilderbeast", Species: "Bewilderbeast", Class: "Tidal", Description: "The benevolent and leonine king of all dragons"},
	{ID: 22, Name: " ", Species: "Death Song", Class: "Mystery", Description: "Enticing and siren-like, this species of dragon is decidedly solitary"},
	{ID: 23, Name: " ", Species: "Dramillion", Class: "Mystery", Description: "Imitative"},
	{ID: 24, Name: " ", Species: "Red Death", Class: "Stoker", Description: "The Red Death was a Titan Wing dragon secretly responsible for centuries of human-dragon conflict, using its commanding presence to force other dragons to raid villages and bring it food. It reigned supreme from its volcanic lair on Dragon Island until the Berk Vikings and Toothless found it. The enormous dragon had to shatter its mountain home to emerge. Ultimately, Hiccup and Toothless discovered and exploited its only vulnerable spot—its insides—leading to its defeat"},
	{ID: 25, Name: " ", Species: "Boneknapper", Class: "Mystery", Description: "This Mystery Class scavenger covers itself in bones to shield its delicate body. Its choice of armor makes it unpopular with other Dragons! The Boneknapper is well-protected in its armor while it gets close and delivers a potent stream of fire to its fleeing opponents"},
	{ID: 26, Name: " ", Species: "Buffalord", Class: "Mystery", Description: "Don't let its docile demeanor fool you! Thought to be extinct, this already massive dragon will double in size and will become extremely aggressive if removed from its food source. When in battle (or away from its food) this dragon can puff up to reveal spikes covering it from head to tail. If it's not blasting these spikes, it's snorting out flames"},
	{ID: 27, Name: " ", Species: "Catastrophic Quaken", Class: "Boulder", Description: "Catastrophic Quakens are known for their cruel attitudes. They don't let anyone get in their way, and they'll go out of their way to wreak havoc on their target. Catastrophic Quakens eat more rocks than any other in their class! They also have a nasty habit of spitting up digested rocks at attackers in the form of hot lava"},
	{ID: 28, Name: " ", Species: "Cavern Crasher", Class: "Mystery", Description: "The Cavern Crasher flings flammable mucus and scurries across underground catacombs in search of its favorite food: Firecomb"},
	{ID: 29, Name: " ", Species: "Changewing", Class: "Mystery", Description: " Unlike other dragons the Changewing spits acid instead of fire. Even newly-hatched Changewings have the ability to spit acid onto any potential threat. They got their name from the changing color of their scales which they use as camouflage"},
	{ID: 30, Name: " ", Species: "Crimson Goregutter", Class: "Boulder", Description: "Although Goregutters have impressive sets of antlers and axe-shaped tails, they are gentler than they appear and like to be left in peace. In battle, however, they have the ability to spew molten lava onto their antlers before ramming opponents with fiery force"},
	{ID: 31, Name: " ", Species: "Deathgripper", Class: "Strike", Description: "Deathgrippers are a one-of-a-kind dragon, born with venomous pincer tails which are eerily to those of a venomous scorpion. These dragons love spending time up in the air, helping Vikings reinforce dragon riding skills as they go"},
	{ID: 32, Name: " ", Species: "Fireworm", Class: "Stoker", Description: "Each Fireworm colony holds only one female, the Queen! Although rare, when a new female is born, she sets out to establish her own colony"},
	{ID: 33, Name: " ", Species: "Flightmare", Class: "Mystery", Description: "Instead of shooting fire, this Dragon from the Mystery Class emits a toxic mist that paralyzes its foes"},
	{ID: 34, Name: " ", Species: "Hobgobbler", Class: "Mystery", Description: "Believed by many to bring bad luck, Hobgobblers had a nasty reputation due to superstitious assumptions"},
	{ID: 35, Name: " ", Species: "Razorwhip", Class: "Sharp", Description: "Try to get on this Dragon's good side... if you can find one. Their toxic breath and razor-sharp tail make them dangerous from top to bottom"},
	{ID: 36, Name: " ", Species: "Sand Wraith", Class: "Tidal", Description: " A Tidal Class expert in camouflage that buries itself in the sand. It's a good way to surprise their prey"},
	{ID: 37, Name: " ", Species: "Scauldron", Class: "Tidal", Description: "This huge underwater dragon is a speedy and silent swimmer. Instead of breathing fire, Scauldron spits scalding hot water at its prey"},
	{ID: 38, Name: " ", Species: "Screaming Death", Class: "Boulder", Description: " Born every one hundred or so years, the Screaming Death has all the strengths of its subordinate cousin, the Whispering Death, with none of its weaknesses. It is the most powerful dragon Berk has faced since the Red Death"},
	{ID: 39, Name: " ", Species: "Scuttleclaw", Class: "Sharp", Description: "Scuttleclaws are rambunctious and hyperactive dragons, which is why they are so darn difficult to control in flight, but they're still very cute"},
	{ID: 40, Name: " ", Species: "Sentinel", Class: "Boulder", Description: "Although sightless, the Sentinels still keep close watch over the dragon Graveyard on the Isle of Vanaheim. These vast, stony Dragons show little room for weakness, but a clever mind can exploit their blindness. Be wary, however; they have a keen sense of "},
	{ID: 41, Name: " ", Species: "Shellfire", Class: "Tidal", Description: "The Shellfire glides through the ocean at incredible speeds and shrugs off attacks with its durable carapace, delivering devastation with its protruding horns"},
	{ID: 42, Name: " ", Species: "Shovelhelm", Class: "Boulder", Description: "Instead of charging straight into battle, Shovelhelms like to stand back and evaluate the situation first. That way, they can figure out the best way to fight"},
	{ID: 43, Name: " ", Species: "Singetail", Class: "Stoker", Description: "It's best not to get in a Singetail's way. These territorial Dragons can blast fire out of their jaws, gills, and tails"},
	{ID: 44, Name: " ", Species: "Slitherwing", Class: "Mystery", Description: "Slitherwings tend to hunt in packs. Just like regular snakes, their bright coloration indicates its venom level. The more colorful they are, the deadlier the attack"},
	{ID: 45, Name: " ", Species: "Small Shadow Wing", Class: "Stoker", Description: "And they are quicker than we are, plus, they're smart. And they work as a team"},
	{ID: 46, Name: " ", Species: "Smothering Smokebreath", Class: "Mystery", Description: "The Smothering Smokebreath likes to stay hidden. It pumps out smoke from its skin to create a thick cloak of fog"},
	{ID: 47, Name: " ", Species: "Snafflefang", Class: "Boulder", Description: "With their diamond-sharp teeth, Snafflefangs love to gnaw on geodes in the same way a dog might chew on its favourite bone"},
	{ID: 48, Name: " ", Species: "Snifflehunch", Class: "Tracker", Description: "These inquisitive Dragons don't know the meaning of personal space! They'll get as close as they can to sniff out if someone's friend or foe"},
	{ID: 49, Name: " ", Species: "Snow Wraith", Class: "Strike", Description: "The Snow Wraith uses its thermal vision to find its prey. So if things get heated, find some snow to take cover and cool off"},
	{ID: 50, Name: " ", Species: "Songwing", Class: "Strike", Description: "Small body but big wings"},
	{ID: 51, Name: " ", Species: "Speed Stinger", Class: "Sharp", Description: "They don't fly but they're fast. Faster than any dragon I've ever seen, and they hide in the shadows"},
	{ID: 52, Name: " ", Species: "Submaripper", Class: "Tidal", Description: "Hailing from the Tidal Class, the Submaripper has sent many a Viking to a watery grave with its ability to create inescapable whirlpools"},
	{ID: 53, Name: " ", Species: "Thunderclaw", Class: "Tracker", Description: "hunderclaws are pretty cute. Feisty, but cute"},
	{ID: 54, Name: " ", Species: "Thunderdrum", Class: "Tidal", Description: "This reclusive dragon inhabits sea caves and dark tide pools. When startled, the Thunderdrum produces a concussive sound that can kill a man at close range"},
	{ID: 55, Name: " ", Species: "Triple Stryke", Class: "Strike", Description: "This giant Strike Class Dragon's three tails can slash through its enemies or snake around its prey"},
	{ID: 56, Name: " ", Species: "Typhoomerang", Class: "Stoker", Description: "Much like the rings inside a tree, the scorch mark can tell you the age and thus the size of the Typhoomerang in question"},
	{ID: 57, Name: " ", Species: "Windgnasher", Class: "Tracker", Description: "With a strong enough wind, these humped back dragons can pick up a scent from anywhere in the archipelago or beyond"},
	{ID: 58, Name: " ", Species: "Windstriker", Class: "Sharp", Description: "A Sharp Class skydiver that is literally full of hot air! Instead of breathing fire they shoot super-heated blasts of air that sets their foes ablaze"},
	// {ID: 55, Name: " ", Species: "", Class: "", Description: ""},
}
